name: Deploy Storybook on Github Pages

on:
  push:
    branches:
      - storybook-replacement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install main pkg deps
        run: |
          npm ci

      - name: Install docs pkg deps
        run: |
          npm ci
        working-directory: docs

      - name: Build docs
        run: |
          NODE_ENV=production npm run build
        working-directory: docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages-new
          folder: docs/dist
